kind: Deployment
apiVersion: apps/v1
metadata:
  name: yujian-activity
  namespace: yujian
  labels:
    app: yujian-activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yujian-activity
  template:
    metadata:
      labels:
        app: yujian-activity
    spec:
      containers:
        - name: yujian-activity
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
          ports:
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
